### ISSUE TITLE
yldl cog

### ISSUE THREAD

**Issue by cens0r3d** [kaogurai/cogs#12]
Mfus.tk is not working down/so the cog as well.

**Comment by Ryan5453** [comment]
Fixed in v1.0.7

There really isn't many open public URL shorteners that isn't behind cloudflare or a captcha so the one I had to use does have this temporary redirect page which is kinda annoying but it stills works, but lmk if anyone finds a better one.

**Comment by cens0r3d** [comment]
the links are working, but downloading inside discord wont dl the proper file just a empty file.mp4

**Comment by Ryan5453** [comment]
My bad, fixed in v1.0.8
