### ISSUE TITLE
[Suggestion][AiArt] Set NSFW channel and prevent DM question

### ISSUE THREAD

**Issue by DJTOMATO** [kaogurai/cogs#14]
So yeah, If there's a ~~NSFW~~ normal channel, could it be possible that the question to send it to DM would be ignored and just be posted in that channel?

Or if it's too complex, just make a command like ``!aiart ignorensfw #channel`` so the image is posted on the spot?

In my experience, the #bots channel is not nsfw, so the idea is to be able to skip that NSFW filter, because it's pretty false-positive and annoying for users when they're just trying to share images.

Thanks in advance!

**Comment by Ryan5453** [comment]
Are you updated to the latest version? This is already the existing functionality.

**Comment by DJTOMATO** [comment]
> Are you updated to the latest version? This is already the existing functionality.

Yeah, I just triple checked. It's my fault, I made several typos while writing this thread, I've updated the OP. 

My apologies :(

**Comment by Ryan5453** [comment]
I won't be adding this. Feel free to fork if you'd like, but adding this could go directly against Discord's TOS by allowing NSFW media to be sent in non-nsfw channels, even if the main usecase is for false positives.
