### ISSUE TITLE
[SmartLyrics] Lyrics isnt showing the lyrics

### ISSUE THREAD

**Issue by cool-aid-man** [kaogurai/cogs#18]
Hey rayan, 
Hope you're doing well! 

So the lyrics aren't showing the lyrics for a couple of days now, VC, Spotify nothing works. and it says,
![image](https://user-images.githubusercontent.com/84676543/228007418-76b7ed85-f25b-4851-968a-f5017690ecb0.png)

Even if you give it a query to search for, it says the same thing. 
Could you pls check if there's anything wrong with it or not!

**Comment by Ryan5453** [comment]
Fixed
