### ISSUE TITLE
[BUG] [Lyrics] [p]lyrics command's query argument is not greedy

### ISSUE THREAD

**Issue by cswimr** [kaogurai/cogs#21]
### Steps to Reproduce:

1. Use the ``[p]lyrics`` command to search for a song with more than one word in the name.
2. Have it give you the completely wrong song because it only searched for the first word you provided.

You can fix this by wrapping the query in ``" "``, but this harms usability. I'll be opening a PR shortly to provide a fix for the issue.

**Comment by Ryan5453** [comment]
fixed

**Comment by cswimr** [comment]
oh my goodness you commented like instantly LOL mb

**Comment by Ryan5453** [comment]
np, got the notification from the gh app and just edited it there lol

thx for making an issue, must've fucked it up when refactoring the cog to use genius bc i removed some args
