### ISSUE TITLE
[lyrics] lyrics not checking for `voice channel` songs

### ISSUE THREAD

**Issue by cool-aid-man** [kaogurai/cogs#23]
Hey ryan,
Noticed some issue on SmartLyrics,
So the `lyrics` is not checking for **voice channel** songs that are playing at the moment, however it does check and works fine on `query`, `spotify status`. (couldn't check for `last.fm` as i don't have it but think it's working fine as well)

So only the voice channel is the issue.

**Comment by Ryan5453** [comment]
Are you using the stock Red audio cog or Draper's pylav cog?

**Comment by cool-aid-man** [comment]
Stock red audio cog

**Comment by Ryan5453** [comment]
I can't reproduce this - it works for me.

<img width="603" alt="image" src="https://github.com/kaogurai/cogs/assets/50505980/fa598429-2755-44bf-a192-5b975a18b638">

Just to make sure, you are in the same voice channel as the bot, right?

**Comment by cool-aid-man** [comment]
Here's my testing.
My Settings
> core audio cog,
> Red - 3.5.2, Py - 3.11.3, dpy - 2.2.3

![image](https://github.com/kaogurai/cogs/assets/84676543/b5dbe34c-0e3f-464d-9906-88beab212a16)
and yes I'm on the same channel where the bot is in

**Comment by Ryan5453** [comment]
If you update the cog, it should hopefully work now. It now removes extras from the song title like the `(Lyrics)` which should make it able to find results.

**Comment by cool-aid-man** [comment]
fixed thanks ryan
