### ISSUE TITLE
[Search] cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by cool-aid-man** [kaogurai/cogs#29]
Hi Ryan, 
Getting several and random error on `google` command:
Leaving the tracebacks here:
```py
Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.local/share/Red-DiscordBot/data/pp/cogs/CogManager/cogs/search/search.py", line 95, in websearch
    sidebar, results = await self._search_qwant(ctx, "web", 10, query)
    ^^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: cannot unpack non-iterable NoneType object
```
> - This came from `<p>google hello` or, `<p>google h`

**Comment by Ryan5453** [comment]
i think changing line 68 to return None, None might fix it but i’m away from my computer for a week, but if you want to try it i can marge it

**Comment by cool-aid-man** [comment]
Sure, You are right, I made the change on `line 68` to `return None, None` and it stopped the cog from erroring tho getting `"No results found."` on pretty much every single queries (guessing the API is not available at this very moment) 

Should I go ahead and `pr` the change! 
![image](https://github.com/user-attachments/assets/5a61d662-6c4c-4885-b2c2-441234b40906)

**Comment by Ryan5453** [comment]
Yes please that would be great, I won’t be able to actually look into why the error is happening for a few days though. I’ll keep this open until I fix it

**Comment by cool-aid-man** [comment]
Sure thing, Done, Pr-ed.
And all good, take your time 👍

**Comment by Ryan5453** [comment]
There doesn't seem to be an issue from my end - the cog seems to work fine so it might have just been a temporary glitch on Qwant's end. Let me know if it's still not working and I can look into it more.

**Comment by cool-aid-man** [comment]
Yeah, I tested it later and even today & everything seems to be working just fine, so yes it was definitely the API at that time that had some issues!
