### ISSUE TITLE
[Suggestion][Radio] titles

### ISSUE THREAD

**Issue by SvalbardCoder** [kaogurai/cogs#6]
Hey there! You told me to make an issue, so here I am. My idea is an option to have "titles" for the radio stations, I've made a bit of an embed example that I've attached in images. The reason for this is that sometimes the "snippet" names we give to the stations don't match the actual name, so it could be good for navigation, this could also be optional as I know how some people would be happy with how it is right now.

![Screenshot 2022-09-15 200437](https://user-images.githubusercontent.com/107149169/190488166-455ebf0a-1dd0-4d56-ad1c-4fcf07e6a817.png)

**Comment by Ryan5453** [comment]
It's not a bad idea but I'm not really inclined to add this because it would make storing the data slightly more difficult
